config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  get 'about', to: 'about#index'

  resources :books
  resources :authors
  resources :categories
  resources :publishers

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  belongs_to :author
  belongs_to :publisher
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books

  validates :name, presence: true,
            length: { minimum: 3 }
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = 'About Us'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
 
  def index
  end

  def show
  end

  def new
    @page_title = 'Add Author'
    @author = Author.new
  end

  def edit
  end

  def create
    @author = Author.new(author_params)
    @author.save

    redirect_to authors_path
  end

  def update
  end

  def destroy
  end

   private
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 
  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end 

  def new
    @page_title = 'Add Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def edit
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book created"
      redirect_to books_path
    else
      flash[:alert] = "Book not created"
      render :new
    end
  end

  def update
  end

  def destroy
  end

  private
    def book_params
      params.require(:book).permit(:title, :category, :author, :publisher_id, :isbn, :price, :year, :buy, :format, :excerpt, :pages)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books = @category.books
  end

  def new
    @page_title = 'Add Category'
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category created"
      redirect_to categories_path
    else
      flash[:alert] = "Category not created"
      render :new
    end
    
  end

  def update
  end

  def destroy
  end
  
  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
 
  def index
  end

  def show
  end

  def new
    @page_title = 'Add Publisher'
    @publisher = Publisher.new
  end

  def edit
  end

  def create
    @publisher = Publisher.new(publisher_params)
    @publisher.save

    redirect_to publishers_path
  end

  def update
  end

  def destroy
  end

   private
    def publisher_params
      params.require(:publisher).permit(:name)
    end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Sample text</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/new.html.erb
<h1>Authors#new</h1>
<p>Find me in app/views/authors/new.html.erb</p>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<%= render 'partials/books' %>

app/views/books/new.html.erb
<h2>Add New Book</h2>

<%= form_for @book do |f| %>
  <div class='form-group'>
    <%= f.label :title %><br/>
    <%= f.text_field :title, class: 'form-control' %><br/>
  </div>
  <div class='form-group'>
    <%= f.label :isbn %><br/>
    <%= f.text_field :isbn, class: 'form-control' %><br/>
  </div>
  <div class='form-group'>
    <%= f.label :categories %><br/>
    <%= f.select :category_id, Category.all.collect { |x| [x.name, x.id]}, {:include_blank => 'Select one'}, class: 'form-control' %><br/>
  </div>
  <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/books/show.html.erb
<div id="books-show">
  <h2><%= @book.title %></h2>
  <div class="books-show-left">
    <%= image_tag('') %>
  </div>
  <div class="books-show-right">
    <h3>Book Info</h3>
    <ul>
      <li><strong>Category: </strong><%= @book.category.name %></li>
      <li><strong>Author: </strong>Some twat</li>
      <li><strong>ISBN: </strong><%= @book.isbn %></li>
    </ul>
    <%=link_to "",'XXX', class: 'btn btn-success', target: 'XXX' %>
  </div>
  <div class="clearfix"></div>
  <h4>XXXXXX</h4>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for @category do |f| %>
  <div class='form-group'>
    <%= f.label :name %><br/>
    <%= f.text_field :name, class: 'form-control' %><br/>
  </div>

  <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<%= render 'partials/books' %>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p>Copyright &copy 2014, all rights reserved </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Home', root_path %></li>
        <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'About', about_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Book', new_book_path %></li>
            <li><%= link_to 'Category', new_category_path %></li>
            <li><%= link_to 'Author', new_author_path %></li>
            <li><%= link_to 'Publisher', new_publisher_path %></li>
          </ul>
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<header>
  <div class="container">
  <h1>The Bookstore <small><%= @page_title ? @page_title : "Welcome" %></small></h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? @page_title : "Welcome" %> | The Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<section>
  <div class="container">
    <div clas="row">
      <div class="col-md-8">
        <% if flash[:notice] %>
          <div class="alert alert-success"><%= flash[:notice] %></div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert alert-danger"><%= flash[:alert] %></div>
        <% end %>
        <%= yield %>
      </div>
      <div class="col-md-4">
        <%= render 'partials/sidebar' %>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/partials/_books.html.erb
<div id="books-index">
  <% @books.each_slice(4) do | book| %>
    <div class="row">
      <% book.each do |book| %>
        <div class="col-md-3 col-sm-3">
          <%= book.title%><br/>
          <%= book.isbn %><br/>
          <%= book.publisher_id %><br/>
          <%= link_to 'Read More', book_path(book), class: "btn btn-primary"%><br/>
        </div>
      <% end %>
    </div>
  <% end %> 
</div>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
  <div class="well">
    <h3>Location Info</h3>
    <ul>
      <li>The Bookstore</li>
      <li>House 15, 26th Street</li>
      <li>Hong Lok Yuen</li>
      <li>New Territories</li>
      <li>Phone: (852) 5555 5555</li>
      <li>Email: contact@thebookstore.com</li>
    </ul>
  </div>
<% end %>

<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
<div class="list-group">
  <% @categories.order('name').each do |category| %>
    <%= link_to category.name, category_path(category.id), class: 'list-group-item' %>
  <% end %>
</div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

app/views/publishers/index.html.erb
<h1>Publishers#index</h1>
<p>Find me in app/views/publishers/index.html.erb</p>

app/views/publishers/new.html.erb
<h1>Publishers#new</h1>
<p>Find me in app/views/publishers/new.html.erb</p>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>